[pytest]
addopts = -s -v
python_files=test_*.py
python_classes=Test*
python_functions=test_*

markers=
    ui: Запускает все UI автотесты
    smoke: запускает смоук-тесты
    regression: запускает регрессионные тесты
    slow: запускает медленные тесты
    registration: запускает тесты по регистрации
    critical: запускает критичные тесты
    authorization: запускает тесты на авторизацию
    courses: запускает тесты по курсам
    dashboard: запускает тесты, связанные с рабочей панелью