from enum import Enum

class AllureTag(str,Enum):
    COURSES = "COURSES"
    AUTHORIZATION = "AUTHORIZATION"
    REGRESSION = "REGRESSION"
    USER_LOGIN = "USER_LOGIN"
    NAVIGATION = "NAVIGATION"
    DASHBOARD = "DASHBOARD"
    REGISTRATION = "REGISTRATION"